[package]
name = "cli"
version = "0.1.0"
edition = "2021"
description = "CLI for S3 backup and restore"

[dependencies]
core = { path = "../core" }
anyhow = "1.0"
aws-config = "0.56"
aws-sdk-s3 = "0.30"
clap = { version = "4.3", features = ["derive", "env"] }
dotenv = "0.15"
env_logger = "0.10"
log = "0.4"
tokio = { version = "1.28", features = ["full"] }