name: Debug Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run with debug logging"
        required: false
        default: false
        type: boolean

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event name: ${{ github.event_name }}"
          echo "GitHub repository: ${{ github.repository }}"
          env

      - name: List repository contents
        run: |
          ls -la
          find .github -type f -name "*.yml" 2>/dev/null || echo "No workflow files found"

      - name: Check file structure
        run: |
          echo "Checking workflow directory structure"
          if [ -d ".github/workflows" ]; then
            echo "✅ Workflows directory exists"
            ls -la .github/workflows
          else
            echo "❌ .github/workflows directory not found"
            mkdir -p .github/workflows
            echo "Created .github/workflows directory"
          fi

      - name: Echo success
        run: echo "Debug workflow completed successfully"
